
robot_radius: 0.28 # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

map_type: costmap
publish_frequency: 1.0
transform_tolerance: 0.5
obstacle_layer:
  enabled: true  
  obstacle_range: 2.5
  raytrace_range: 2.5
  observation_sources: scan 
  scan:
    data_type: LaserScan
    sensor_frame: laser
    topic: scan
    marking: true
    clearing: true
    expected_update_rate: 0.2


#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  2.58  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.5  # max. distance from an obstacle at which costs are incurred for planning paths.





