#Configuation for robot odometry EKF
#
frequency: 50
two_d_mode: true
odom0: /retailbot_velocity_controller/odom

odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
               
odom0_differential: false

imu0: /imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_differential: false

#publish_tf: false
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
map_frame: map